// lição de musica
Console.WriteLine("TITULO DA MUSICA");
Console.WriteLine(@"Quer Voar
Canção de Matuê ‧ 2021");
Console.ForegroundColor = ConsoleColor.Red;
Thread.Sleep(2000);
Thread.Sleep(2000);
Console.WriteLine("Palaze, what you cookin'?");
Console.WriteLine("Passa o Bic (o Bic), põe no ar");
Console.WriteLine("Minha bitch (my bitch), quer voar");
Console.WriteLine("Botei no sport pro escapamento estralar (woah)");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.WriteLine("Troquei o Corsa num Porsche, quem 'tava lá?");
Thread.Sleep(3000);
Thread.Sleep(3000);
Console.WriteLine("Queimando gasolina, ah-yah");
Console.WriteLine("Famoso comedor de prima, ah-yah");
Console.ForegroundColor = ConsoleColor.Black;
Console.WriteLine("Sexo encanta, sorriso me hipnotiza-iza");
Console.WriteLine("Sempre quis foder a sua brisa");
Thread.Sleep(1000);
Thread.Sleep(1000);
Thread.Sleep(4000);
Thread.Sleep(1000);
Thread.Sleep(1000);
Console.WriteLine("E ela diz fode, fode (fode, fode)");
Console.WriteLine("Lambe, lambe, mete bem ");
Console.WriteLine("Nunca vi tempo ruim, chupada dentro da Benz");
Console.WriteLine("Eu sou um sujeito ruim, não dou moral pra ninguém");
Console.WriteLine("Quer um troco? Tira esse roupão, me entretém, yeah");
Console.ForegroundColor = ConsoleColor.Black;
Console.ResetColor();
Thread.Sleep(1000);
Thread.Sleep(1000);
Thread.Sleep(1000);
Console.WriteLine("(Uh) Balança, bonita");
Console.WriteLine("Transa na cabine que ela gosta de gritar");
Console.WriteLine("Se eu falar que eu amo, ela ainda acredita");
Console.WriteLine("Bola mais um que essa porra é rum, não é Guaravita");
Thread.Sleep(1000);
Thread.Sleep(1000);
Thread.Sleep(4000);
Thread.Sleep(1000);
Console.WriteLine("Passa o Bic (o Bic), põe no ar");
Console.WriteLine("Minha bitch (my bitch), quer voar");
Console.WriteLine("Botei no sport pro escapamento estralar (woah)");
Console.WriteLine("Troquei o Corsa num Porsche, quem 'tava lá?");
Console.WriteLine("Queimando gasolina, ah-yah");
Console.WriteLine("Famoso comedor de prima, ah-yah");
Console.WriteLine("Sexo encanta, sorriso me hipnotiza-iza");
Console.WriteLine("Sempre quis fuder a sua");
Console.WriteLine("Vem pra cá (pra Fortal City)");
Console.WriteLine("Ampliar (fumar do bom)");
Thread.Sleep(4000);
Thread.Sleep(4000);
Console.ResetColor();
Console.WriteLine("A visão");
Console.WriteLine("Eu sou lenda tipo Don, man");
Console.WriteLine("Saí de Fortal, fui lá fazer meu próprio nome");
Console.WriteLine("E hoje eu fiz uma pilha, dá pra escalar");
Console.WriteLine("Quem não gostou, agora vai ter que aturar");
Console.WriteLine("The gun is on the table, quer aprender inglês? (Uh, woah)");
Console.WriteLine("Ela vem treinar blow com u'a aula por mês (uh, woah)");
Console.WriteLine("Então tome, tome, tome, bebe, bebe, tome, tome");
Console.WriteLine("Só sai do forró quando quiser");
Thread.Sleep(4000);
Thread.Sleep(4000);
Console.WriteLine("The drug is on the table, quer aprender inglês? (Uh, woah)");
Console.WriteLine("2030 e eu aqui rindo de vocês (ha-ha)");
Console.WriteLine("Passa o Bic (o Bic), põe no ar");
Console.WriteLine("Minha bitch (my bitch), quer voar");
Console.WriteLine("Botei no sport pro escapamento estralar (woah)");
Console.ForegroundColor = ConsoleColor.Magenta;
Console.ResetColor();
Thread.Sleep(1000);
Thread.Sleep(1000);
Thread.Sleep(1000);
Console.WriteLine("Troquei o Corsa num Porsche, quem 'tava lá?");
Thread.Sleep(1000);
Console.WriteLine("Queimando gasolina, ah-yah");
Console.WriteLine("Famoso comedor de prima, ah-yah");
Console.ForegroundColor = ConsoleColor.Black;
Console.ResetColor();
Console.WriteLine("Sexo encanta, sorriso me hipnotiza-iza");
Console.WriteLine("Sempre quis foder a sua brisa");
Console.WriteLine("Esse ano ninguém vai me parar, eu sigo, sigo forte");
Console.WriteLine("Bola um temaki bom, é só um tiro e morde");
Console.WriteLine("Caixão de grande porte");
Console.WriteLine("Eu sou um big dog, big money, big loss");
Console.WriteLine("Mas nós nunca perde, pode ficar na bad");
Thread.Sleep(1000);
Thread.Sleep(1000);
Thread.Sleep(4000);
Thread.Sleep(1000);
Thread.Sleep(1000);
Console.ResetColor();
Console.WriteLine("É a (30, 30, 30, 30)");
Console.WriteLine("(30, 30, 30, 30, 30)");
Console.ForegroundColor = ConsoleColor.Yellow;
Console.ResetColor();